# Generated by Django 2.2.2 on 2019-06-22 22:37

from django.db import migrations, models
import phonenumber_field.modelfields
import registration.models
import registration.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('full_name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='full_name')),
                ('region', models.CharField(max_length=50, verbose_name='region')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='phone')),
                ('place_of_study', models.CharField(max_length=50, verbose_name='place of study')),
                ('place_of_work', models.CharField(max_length=50, verbose_name='place of work')),
                ('education', models.CharField(max_length=50, verbose_name='education')),
                ('motivation', models.TextField(blank=True, verbose_name='about')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='teacher')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('avatar', models.ImageField(default='none/blank.jpg', upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', registration.models.UserManager()),
            ],
        ),
    ]
