# Generated by Django 2.2.2 on 2019-06-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='full_name'),
        ),
    ]
