# Generated by Django 2.2.2 on 2019-06-29 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_participations', models.IntegerField(verbose_name='max participations')),
                ('capitan', models.ForeignKey(on_delete='capitam', to=settings.AUTH_USER_MODEL)),
                ('invated', models.ManyToManyField(related_name='invated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('input_data', models.CharField(max_length=250, verbose_name='input data')),
                ('answer', models.CharField(max_length=250, verbose_name='answer')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='crater')),
            ],
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('duration', models.IntegerField(verbose_name='')),
                ('start_olympiad', models.DateTimeField(verbose_name='date of the start olympiad')),
                ('end_olympiad', models.DateTimeField(verbose_name='date of the end olympiad')),
                ('participation_count', models.IntegerField(verbose_name='participation count')),
                ('max_teams', models.IntegerField(verbose_name='max teams')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ManyToManyField(to='olympiad.Task')),
                ('team', models.ManyToManyField(to='olympiad.Team', verbose_name='teams')),
            ],
        ),
    ]
