# Generated by Django 2.2.2 on 2019-07-03 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='invated',
            new_name='invited',
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='team',
            field=models.ManyToManyField(to='olympiad.Team', verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creater'),
        ),
        migrations.AlterField(
            model_name='team',
            name='capitan',
            field=models.ForeignKey(on_delete='capitan', to=settings.AUTH_USER_MODEL),
        ),
    ]
